spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
server.port=${PORT:8080}